### ISSUE TITLE
workarounds install giving permissions error

### ISSUE THREAD

**Issue by rastapapa** [CustomMachines/talkiepi#11]
Not sure if this is correct but Im seeing the following when installing on a pi zero w

> Download is performed unsandboxed as root as file '/root/go/src/github.com/CustomMachines/talkiepi/workarounds/libopenal1-dbg_1.17.2-4_armhf.deb' couldn't be accessed by user '_apt'. - pkgAcquire::Run (13: Permission denied)

**Comment by CustomMachines** [comment]
Hi @rastapapa, it sounds like something has gone wrong. Unfortunately I don't have the time to help you with this right now. Good luck!

**Comment by rastapapa** [comment]
Started over and got it installed. Looks like I had entered sudo -i at one point which is needed in dchote's install and not this one.
