### ISSUE TITLE
Missing faces in STLs and broken blender file?

### ISSUE THREAD

**Issue by anibarro** [CustomMachines/talkiepi#4]
Hello,

First, thanks a lot for the case model, the detail and the fitting is amazing!

I've found a couple of errors in the STL files that make Simplify3D fail to slice the model properly.
The need for the "Keep disconnected faces" option exists because at least one face is missing in the border of the button's gap, and Simplify 3D is removing the broken geometry.
The other missing face is in the bottom part, a large section containing the USB connector.
I had to fix them in the STL file because the .blend file crashes Blender on load.

Cheers

**Comment by CustomMachines** [comment]
Hi anibarro, thanks for letting me know about these issues. I've uploaded fixed STL files and deleted the corrupt Blender file. I don't have access to the original Blender file so I can't uploaded a fixed version.

**Comment by anibarro** [comment]
Great, they slice perfectly now :)
